services:
  voices:
    container_name: voices
    image: usdotfhwastoldev/voices:pilot2-event0-0.0.2
    tty: true 
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthroity
      - VOICES_CARLA_CONTAINER=carla
      - VOICES_SITE_CONFIG=andrew_docker.config
      - VOICES_START_EM=true
      - VOICES_START_CONSOLE=true
      - VOICES_START_CANARY=true
      - VOICES_START_TDCS=false
      - VOICES_START_DATAVIEW=false
      - VOICES_START_SCENARIO_PUBLISHER=false
      - VOICES_START_TENA_CARLA_ADAPTER=false
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/carma/voices-poc:/home/voices-poc