services:
  voices:
    container_name: voices
    image: usdotfhwastoldev/voices:pilot2-event0-latest
    tty: true 
    network_mode: "host"
    environment:
      - DISPLAY=$DISPLAY
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=~/.Xauthority
      - VUG_SITE_CONFIG_FILE=${VUG_SITE_CONFIG_FILE}
    env_file:
      - ${HOME}/.voices_site_config
      - ${HOME}/.voices_scenario_config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/voices-poc/voices-poc:/home/voices-poc